GET http://localhost:8080/api/product/1

###
GET http://localhost:8080/api/product/all

###

GET http://localhost:8080/api/group/1

###

GET http://localhost:8080/api/group/all

###

DELETE http://localhost:8080/api/group/2





